CREATE TABLE [dbo].[rentals]
(
	[rentalID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [username] NVARCHAR(30) NOT NULL,
	[setID] INT NULL, 
    [productID] INT NULL, 
    [rentalAmount] INT NOT NULL, 
    [rentalCreated] DATETIME NOT NULL, 
    [rentalStart] DATETIME NOT NULL, 
    [rentalEnd] DATETIME NOT NULL, 
    [rentalDelivery] DATETIME NULL, 
    [rentalReturned] DATETIME NULL, 
    [rentalCanceled] DATETIME NULL, 
    [rentalFree] DATETIME NULL, 
    [rentalCanceledUserName] NVARCHAR(30) NULL, 
    [rentalNote] NVARCHAR(50) NULL, 
    FOREIGN KEY (username) REFERENCES users(username),
	FOREIGN KEY (setID) REFERENCES sets(setID),
	FOREIGN KEY (productID) REFERENCES products(productID),
)
